apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-collector-daemonset
  namespace: default
  labels:
    app: opentelemetry
    app.kubernetes.io/component: oteld-daemonset
spec:
  selector:
    matchLabels:
      app: opentelemetry
      app.kubernetes.io/component: oteld-daemonset
  template:
    metadata:
      labels:
        app: opentelemetry
        app.kubernetes.io/component: oteld-daemonset
    spec:
      serviceAccountName: otelcontribcol
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.133.0
        command:
          - "/otelcol-contrib"
          - "--config=/etc/otelcol/config.yaml"
        ports:
        - name: prometheus
          containerPort: 9090
          protocol: TCP
        - name: otlp-grpc
          containerPort: 4317
          protocol: TCP
        - name: otlp-http
          containerPort: 4318
          protocol: TCP
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: DT_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: dynatrace
              key: dynatrace_oltp_url
        - name: DT_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: dynatrace
              key: dt_api_token
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: CLUSTERNAME
          valueFrom:
            secretKeyRef:
              name: dynatrace
              key: clustername
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/component']
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=$(OTEL_SERVICE_NAME)
        volumeMounts:
        - name: config
          mountPath: /etc/otelcol
        - mountPath: /var/log
          name: varlog
          readOnly: true
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - name: tetra-log
          mountPath: "/var/run/cilium/tetragon/"
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: config
        configMap:
          name: otel-collector-daemonset-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: tetra-log
        hostPath:
          path: "/var/run/cilium/tetragon/"
