{{- if and .Values.global.codespace .Values.gatewayAPI.enabled }}
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: fixed-nodeport-params
  namespace: {{ .Values.global.namespace }}
spec:
  kube:
    service:
      type: NodePort
{{- end }}